wekan-db:
  tty: true
  command:
  - mongod
  - --smallfiles
  - --oplogSize
  - '128'
  image: mongo:3.2.12
  volumes:
  - ${VOL_PREFIX}-weekan-db-data:/data/db
  - ${VOL_PREFIX}-weekan-db-conf:/data/configdb
  stdin_open: true
  labels:
    io.rancher.container.pull_image: always
wekan-app:
  environment:
    MONGO_URL: ${mongo_url}
    ROOT_URL: ${root_url} 
  image: wekanteam/wekan    
  labels:
    io.rancher.container.pull_image: always