#GOGS: git service
gogs-app:
    image: gogs/gogs:0.11.34
    labels:
      io.rancher.container.pull_image: always
    links:
        - gogs-db
    volumes:
        - ${VOL_PREFIX}-gogs-app:/data
    volume_driver: ${VOL_DRIVER}

gogs-db:
    image: mysql:5.7
    labels:
      io.rancher.container.pull_image: always
    volumes:
        - ${VOL_PREFIX}-gogs-db:/var/lib/mysql 
    volume_driver: ${VOL_DRIVER}
    environment:
        MYSQL_ROOT_PASSWORD: ${GOGS_PASSWORD}
        MYSQL_DATABASE: ${GOGS_DB}